version: '2.1'
networks:
  stream-store:
    name: stream-store
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - stream-store
    ports:
      - '20091:5432'
